/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    @Override
    public void enable() {
        HienthiAnswer.setEnabled(true);
        number0.setEnabled(true);
        Number1.setEnabled(true);
        Number2.setEnabled(true);
        Number3.setEnabled(true);
        Number4.setEnabled(true);
        Number5.setEnabled(true);
        Number6.setEnabled(true);
        number7.setEnabled(true);
        number8.setEnabled(true);
        number9.setEnabled(true);
        methodDevide.setEnabled(true);
        methodPlus.setEnabled(true);
        methodSubtract.setEnabled(true);
        methodthapphan.setEnabled(true);
        methofmultiple.setEnabled(true);
        methodthapphan.setEnabled(true);
        Quaylai.setEnabled(true);
        xoa.setEnabled(true);
        mothodEqual.setEnabled(true);
        Label1.setEnabled(true);
    }

    @Override
    public void disable() {
        HienthiAnswer.setText("");
        HienthiAnswer.setEnabled(false);
        number0.setEnabled(false);
        Number1.setEnabled(false);
        Number2.setEnabled(false);
        Number3.setEnabled(false);
        Number4.setEnabled(false);
        Number5.setEnabled(false);
        Number6.setEnabled(false);
        number7.setEnabled(false);
        number8.setEnabled(false);
        number9.setEnabled(false);
        methodDevide.setEnabled(false);
        methodPlus.setEnabled(false);
        methodSubtract.setEnabled(false);
        methodthapphan.setEnabled(false);
        methofmultiple.setEnabled(false);
        methodthapphan.setEnabled(false);
        Quaylai.setEnabled(false);
        xoa.setEnabled(false);
        mothodEqual.setEnabled(false);
        Label1.setText("");
        Label1.setEnabled(false);
        

    }
    int caculation;
    double num, ans;
    int x;

    public void Caculating() {
        switch (caculation) {
            case 1 -> {
                ans = num + Double.parseDouble(HienthiAnswer.getText());
                HienthiAnswer.setText(Double.toString(ans));
            }
            case 2 -> {
                ans = num - Double.parseDouble(HienthiAnswer.getText());
                HienthiAnswer.setText(Double.toString(ans));
            }

            case 3 -> {
                ans = num * Double.parseDouble(HienthiAnswer.getText());
                HienthiAnswer.setText(Double.toString(ans));
            }

            case 4 -> {
                if (Double.parseDouble(HienthiAnswer.getText())==0){
                    JOptionPane.showMessageDialog(null, "số chia không thể bằng 0");
                }
                else {
                ans = num / Double.parseDouble(HienthiAnswer.getText());
                HienthiAnswer.setText(Double.toString(ans));
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        Label = new javax.swing.JLabel();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        methodPlus = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        methodSubtract = new javax.swing.JButton();
        methofmultiple = new javax.swing.JButton();
        Number3 = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number1 = new javax.swing.JButton();
        methodDevide = new javax.swing.JButton();
        mothodEqual = new javax.swing.JButton();
        methodthapphan = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        Quaylai = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        MethodOn = new javax.swing.JRadioButton();
        MethodOfff = new javax.swing.JRadioButton();
        HienthiAnswer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Label.setText("null");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caculator");

        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number8.setText("8");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        methodPlus.setText("+");
        methodPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodPlusActionPerformed(evt);
            }
        });

        Number4.setText("4");
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number5.setText("5");
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number6.setText("6");
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        methodSubtract.setText("-");
        methodSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodSubtractActionPerformed(evt);
            }
        });

        methofmultiple.setText("*");
        methofmultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methofmultipleActionPerformed(evt);
            }
        });

        Number3.setText("3");
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number2.setText("2");
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number1.setText("1");
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        methodDevide.setText("/");
        methodDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodDevideActionPerformed(evt);
            }
        });

        mothodEqual.setText("=");
        mothodEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothodEqualActionPerformed(evt);
            }
        });

        methodthapphan.setText(".");
        methodthapphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodthapphanActionPerformed(evt);
            }
        });

        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        Quaylai.setText("C");
        Quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuaylaiActionPerformed(evt);
            }
        });

        xoa.setText("x");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(MethodOn);
        MethodOn.setText("ON");
        MethodOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodOnActionPerformed(evt);
            }
        });

        buttonGroup1.add(MethodOfff);
        MethodOfff.setText("OFF");
        MethodOfff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodOfffActionPerformed(evt);
            }
        });

        HienthiAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienthiAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number0, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(Number4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(number7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Number1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Number5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(methodthapphan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(number9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Number6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(methofmultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(methodPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(methodSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mothodEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(methodDevide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MethodOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MethodOfff)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(HienthiAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HienthiAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7)
                    .addComponent(number8)
                    .addComponent(number9)
                    .addComponent(methodPlus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number4)
                    .addComponent(Number5)
                    .addComponent(Number6)
                    .addComponent(methodSubtract))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number1)
                    .addComponent(Number2)
                    .addComponent(Number3)
                    .addComponent(methofmultiple))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number0)
                    .addComponent(methodthapphan)
                    .addComponent(mothodEqual)
                    .addComponent(methodDevide))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quaylai)
                            .addComponent(xoa))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17))
                            .addComponent(MethodOn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(MethodOfff)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "2");
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "5");
    }//GEN-LAST:event_Number5ActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "0");
    }//GEN-LAST:event_number0ActionPerformed

    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "1");
    }//GEN-LAST:event_Number1ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "3");
    }//GEN-LAST:event_Number3ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "8");
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "9");
    }//GEN-LAST:event_number9ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "4");
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + "6");
    }//GEN-LAST:event_Number6ActionPerformed

    private void methodPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodPlusActionPerformed
        num = Double.parseDouble(HienthiAnswer.getText());
        caculation = 1;
        HienthiAnswer.setText("");

        Label1.setText(num + "+");

    }//GEN-LAST:event_methodPlusActionPerformed

    private void methodSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodSubtractActionPerformed
        num = Double.parseDouble(HienthiAnswer.getText());
        caculation = 2;
        HienthiAnswer.setText("");
        Label1.setText(num + "-");


    }//GEN-LAST:event_methodSubtractActionPerformed

    private void methofmultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methofmultipleActionPerformed
        num = Double.parseDouble(HienthiAnswer.getText());
        caculation = 3;
        HienthiAnswer.setText("");
        Label1.setText(num + "*");
    }//GEN-LAST:event_methofmultipleActionPerformed
    
    private void methodDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodDevideActionPerformed
        num = Double.parseDouble(HienthiAnswer.getText());
        caculation = 4;
        HienthiAnswer.setText("");
        Label1.setText(num + "/");
    }//GEN-LAST:event_methodDevideActionPerformed

    private void methodthapphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodthapphanActionPerformed
        HienthiAnswer.setText(HienthiAnswer.getText() + ".");

    }//GEN-LAST:event_methodthapphanActionPerformed

    private void QuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuaylaiActionPerformed
        HienthiAnswer.setText("");
        Label1.setText("");
    }//GEN-LAST:event_QuaylaiActionPerformed

    private void MethodOfffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodOfffActionPerformed
        disable();
    }//GEN-LAST:event_MethodOfffActionPerformed

    private void MethodOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodOnActionPerformed
        enable();
    }//GEN-LAST:event_MethodOnActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        int len = HienthiAnswer.getText().length();
        int number = HienthiAnswer.getText().length() - 1;

        if (len > 0) {
            StringBuilder back = new StringBuilder(HienthiAnswer.getText());
            back.deleteCharAt(number);
            String store;
            store = back.toString();
            HienthiAnswer.setText(store);

        }


    }//GEN-LAST:event_xoaActionPerformed

    private void mothodEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothodEqualActionPerformed

        Caculating();
    }//GEN-LAST:event_mothodEqualActionPerformed
private JButton j=new JButton();
    private void HienthiAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienthiAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HienthiAnswerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HienthiAnswer;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JRadioButton MethodOfff;
    private javax.swing.JRadioButton MethodOn;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Quaylai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton methodDevide;
    private javax.swing.JButton methodPlus;
    private javax.swing.JButton methodSubtract;
    private javax.swing.JButton methodthapphan;
    private javax.swing.JButton methofmultiple;
    private javax.swing.JButton mothodEqual;
    private javax.swing.JButton number0;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables

}
